# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='id',
        ),
        migrations.AlterField(
            model_name='repo',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
